### ISSUE TITLE
Can I translate this repository into Chinese?

### ISSUE THREAD

**Issue by ahonn** [Bogdan-Lyashenko/Under-the-hood-ReactJS#10]
Hi, thank you for your sharing. It pretty good.

Can I translate this repository into Chinese? I will fork this repository translated into Chinese, then replacing the original content.

**Comment by Hangeer** [comment]
不介意的话带一个 hhh

**Comment by Bogdan-Lyashenko** [comment]
Hi, thanks for your interest. Yes, feel free to do that. Can you please put a link to original repo there because in fact it's just half of work, the repo will be updating with new stuff related to Fiber version.

**Comment by ahonn** [comment]
OK, I will put a link to original repository. And  translated new stuff when you updating too.

Thanks : )

**Comment by Bogdan-Lyashenko** [comment]
Great! Thx.

**Comment by linhe0x0** [comment]
@ahonn I'm the maintainer of the [xitu/gold-miner](https://github.com/xitu/gold-miner), we also want to translate this document, could we translate it together? I have sent you an email about the details yesterday, If you have any ideas, please let me know.

**Comment by 6174** [comment]
@Bogdan-Lyashenko  Thank you for your great work, this is awesome!

And I suggest to making i18n just in this repo, so we can all find it and contribute to it!

structure like

```sh
.
└── stack
    └── book
        ├── en-US
        └── zh-CN
```

**Comment by Bogdan-Lyashenko** [comment]
@6174 thanks for your feedback. Yes, sounds reasonable, we can go ahead with that. 
@sqrthree, @ahonn, @Hangeer what do you think? Just thinking not to do double work..

**Comment by sivkun** [comment]
@Bogdan-Lyashenko I have read all the content. It pretty good. I'm looking forward to fiber parts.
I would also like to join the translation program.

**Comment by iFwu** [comment]
Hello @ahonn , also interested in translation to Chinese, how's going there?
