### ISSUE TITLE
Picture Intro.3 has overlapping elements where the name is not visible

### ISSUE THREAD

**Issue by treaz** [Bogdan-Lyashenko/Under-the-hood-ReactJS#13]
for example: Danger.js or ReactEventListener.js
Some of the overlapping elements have visible names

**Comment by Bogdan-Lyashenko** [comment]
@treaz it supposed to be like that, there is no text behind :) I mean, you can see for example this parent path for 'event listener' module is 'src\renderers\dom\client\', so, it contains platform reference 'dom\client', it means that it's platform specific and will be different for other platforms.
