### ISSUE TITLE
Korean translate

### ISSUE THREAD

**Issue by Jae-kwang** [Bogdan-Lyashenko/Under-the-hood-ReactJS#16]
Hello Mr.Bohdan Liashenko. I'm a studying React these days. :)
I'm going to korean translate your 'Under-the-hood-ReactJS' for the purpose of studying and sharing. Can I send Pull requests after I complete it?

**Comment by Bogdan-Lyashenko** [comment]
@Jae-kwang thanks, sure thing, that would be awesome! 

Let's decide what is the best format. I don't want to move existing EN version pages, to not break existing links for people who already use it.
There is the next structure of directories:
/master/stack/
/-/-/book
/-/-/images
I think you can add it on the same level like
/-/-/languages/korean/

So, after that, your directory will be like
/master/stack/languages/korean/

What do you think? Thanks.

**Comment by Jae-kwang** [comment]
@Bogdan-Lyashenko I'm good! If so, should I translate them to "master/stack/languages/korean/book/Part-0.md" and send Pull request?

**Comment by Bogdan-Lyashenko** [comment]
@Jae-kwang , yes, go ahead. Thx. 
Btw, you also can add 'Languages' paragraph in README.md 
like 
## Languages
### Korean

**Comment by Jae-kwang** [comment]
@Bogdan-Lyashenko Okay. I will do that. :)

**Comment by Bogdan-Lyashenko** [comment]
Nice, closing the issue then)
