### ISSUE TITLE
How was this achieved?

### ISSUE THREAD

**Issue by niamleeson** [Bogdan-Lyashenko/Under-the-hood-ReactJS#17]
Thank you very much for the extremely detailed explanation on how React internals work. It must have been a long journey to figure this out.

I am still learning on how to understand other people's source code better, and I have been trying to understand Angular 2's source code.

I was wondering if you would share some insight on how you were able to step through the React source code. Were you running a simple React app and stepping through it? Were you able to somehow get an unminified build? Were you importing React source code and running a simple app? Would it be possible for you to share your setup? Please let me know.

Thank you very much.

**Comment by Bogdan-Lyashenko** [comment]
Hi @niamleeson, thanks.

Well, nothing special, just create small 'old way JS project' 🙂 
I can highlight the next steps I've done for React, you can do the same for Angular:
1. How to use not minified React code? You can try to find it somewhere from CDN or clone React (Angular) project from github and build it. Information how to do that is included in README.md file under 'Contributing guide'. In fact, you anyway need to clone project, if you want to see modules dependencies etc.
2. When you build React project, you will get minified and development (not minified) versions of bundles (files including connected sub-modules). 
3. Take development version bundle (usually it's gonna appear in build|dist folder) and copy it to your 'lib debugging project' directory.
4. Create index.html and simpleCode.js (your code to start to debug from) there as well.
7. Inject copied bundle script into index.html. Something like <script src="react.development.js"> </javascript>
8. After, inject simpleCode.js in the same way.
9. Identify which API endpoints you want to debug. For example, I've debugged ReactDOM.render and this.setState (Component.prototype.setState).
10. Add usage of APIs from (9) to simpleCode.js. Keep it simple as possible. Work with React (Angular) via global variable on window namespace.
11. How actually match code from that big bundle to React ES6 modules from /src folder? Well, that's a bit tricky, requires some manual searching and analyzing. But, it's doable, copy line of code from a bundle and search for it around the module's code, usually, it's single match. 

Pretty much it. Hope that help. Feel free to ask more details about any points if you need. Thanks.

**Comment by niamleeson** [comment]
Thank you for the detailed instructions. I will try this weekend!

**Comment by Bogdan-Lyashenko** [comment]
Cool, thanks. Closing the issue then.
