### ISSUE TITLE
We have translation this repo into Chinese, do you consider add a ch-zn branch for Chinese version?

### ISSUE THREAD

**Issue by leviding** [Bogdan-Lyashenko/Under-the-hood-ReactJS#22]
You can see the Chinese Version at https://github.com/xitu/Under-the-hood-ReactJS/tree/translation.
PR 地址： #24

**Comment by leviding** [comment]
You can see the Chinese Version at https://github.com/xitu/Under-the-hood-ReactJS/tree/translation

**Comment by Bogdan-Lyashenko** [comment]
@leviding nice, great work. Sure, I would be glad to add it. But can you please add it as one more language to the main branch (please check as korean was done). Thanks.

**Comment by leviding** [comment]
@Bogdan-Lyashenko Awesome! Well, we will check the translation again, guarantee the quality of translation. When we finish it, I will add it as one more language to the main branch. About 10 days later.

**Comment by Bogdan-Lyashenko** [comment]
thanks @leviding, awesome work! Merged, closing the issue.
