### ISSUE TITLE
Use "React" instead of "ReactJS"

### ISSUE THREAD

**Issue by impressivewebs** [Bogdan-Lyashenko/Under-the-hood-ReactJS#23]
Just a minor suggestion for this excellent resource: You should refer to React as just "React", which is how they refer to it [on the official website](https://reactjs.org/) and in official documentation. So all instances of "ReactJS" should be changed to just "React".

**Comment by Bogdan-Lyashenko** [comment]
Thanks. Renamed in Read.me
