### ISSUE TITLE
Possible text formatting issue in part 9

### ISSUE THREAD

**Issue by Platonn** [Bogdan-Lyashenko/Under-the-hood-ReactJS#28]
Possibly the part 9 contains a small formatting issue:
> But, what about `setTimeout case`

Maybe it should be:
But, what about `setTimeout` case

**Comment by Bogdan-Lyashenko** [comment]
You are correct :) do you mind to create pull request for this?

**Comment by Platonn** [comment]
Thank you, yes.

**Comment by JXWJS** [comment]
oh my gad . I am new job person.
