### ISSUE TITLE
What does the "clickable" mean in the title?

### ISSUE THREAD

**Issue by NE-SmallTown** [Bogdan-Lyashenko/Under-the-hood-ReactJS#5]
I see many titles like "Part 0 (clickable)" but it can't be clicked,is there anything I missed?

**Comment by Bogdan-Lyashenko** [comment]
It means an image is clickable. Svg scheme is big, and it's better to open it separately in another tab (so you can zoom it etc.). You can click on the image and it will be opened as https://rawgit.com/Bogdan-Lyashenko/Under-the-hood-ReactJS/master/stack/images/0/part-0.svg in new window. Thanks.

**Comment by NE-SmallTown** [comment]
Oh,I see,thanks for your reply.I misunderstand its meaning.I think it could be better if you describe it with "Part 0 (below image are all s clickable)" or describe this in the first of this repo :smile:
