### ISSUE TITLE
which tool you use to draw picture？

### ISSUE THREAD

**Issue by SimplyY** [Bogdan-Lyashenko/Under-the-hood-ReactJS#9]

**Comment by Bogdan-Lyashenko** [comment]
Hi @SimplyY , I use https://www.draw.io/. It works pretty nice. It allows you to have integration with google drive, so you can store schemes as docs in your g-drive and open them with draw.io for editing, all updates saved back to your docs 'on fly'. Pretty cool. It also has many export options.
